name: teste-homer

services:
  database:
    container_name: homer-db
    image: postgres:latest
    restart: always
    # healthcheck:
    # test: [ "CMD-SHELL", "pg_isready -u $${DATABASE_USER}" ]
    # interval: 1m
    # timeout: 15s
    # retries: 5
    # start_period: 30s
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data:rw

volumes:
  gp-data: {}
