# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
import datetime
from typing import Any, Optional


@dataclasses.dataclass()
class LeadInfo:
    """Guarda as preferências do usuário para um empreendimento específico"""
    id: int
    nome_do_usuario: str
    # A quantidade de quartos que a pessoa quer num apto.
    quantidade_de_quartos: Optional[int]
    # Um enum que diz se a pessoa quer sol da manhã ou da tarde
    posicao_do_sol: Optional[Any]
    criado_em: Optional[datetime.datetime]
    atualizado_em: Optional[datetime.datetime]
