# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
import datetime
import enum
from typing import Optional


class Temperaturadolead(str, enum.Enum):
    QUENTE = "Quente"
    FRIO = "Frio"
    MORNO = "Morno"


@dataclasses.dataclass()
class LeadInfo:
    """Guarda as preferências do usuário para um empreendimento específico."""
    id: int
    nome_do_lead: Optional[str]
    # Quantos quartos a pessoa quer na casa.
    quantidade_de_quartos: Optional[int]
    # O bairro em que a pessoa está procurando uma casa.
    bairro: Optional[str]
    # O valor que a pessoa tem para a compra.
    orcamento: Optional[int]
    # O quão "quente" o lead está para uma venda
    temperatura_do_lead: Temperaturadolead
    # A data e hora que a pessoa marcou para ser atendida
    data_e_hora_da_chamada: Optional[str]
    criado_em: Optional[datetime.datetime]
    atualizado_em: Optional[datetime.datetime]
